### ISSUE TITLE
hostname in UNC-in-path URI should use 'host' ABNF rule

### ISSUE THREAD

**Issue by phluid61** [phluid61/internet-drafts#4]
So far I've hand-waved the authority-in-path issue by deferring to Microsoft's UNC definition, but it seems people would prefer to use the `host` ABNF construct to detect UNC-in-path URIs, and then have guidance for translating the host to something UNC accepts (or not) before dereferencing.

**Comment by nicowilliams** [comment]
I have no specific preference here.  But you must pick one since otherwise we'd have two different ways of encoding IDNs in file URIs.

**Comment by phluid61** [comment]
Revision -01 moves UNC-in-path to an optional (non-normative) extension. However the issue still remains open. It's important to note that, according to RFC 3986:

    host        = IP-literal / IPv4address / reg-name
    IP-literal = "[" ( IPv6address / IPvFuture  ) "]"
    IPvFuture  = "v" 1*HEXDIG "." 1*( unreserved / sub-delims / ":" )

but path doesn't allow "[" or "]", so I can't even use `host` in the path.

Perhaps I need to recreate the whole thing with `%5B` and `%5D`

**Comment by phluid61** [comment]
Regarding IDNA, RFC 3986 says:

    The reg-name syntax allows percent-encoded octets in order to
    represent non-ASCII registered names [...].  Non-ASCII
    characters must first be encoded according to UTF-8 [STD63], and then
    each octet of the corresponding UTF-8 sequence must be percent-
    encoded to be represented as URI characters.

So IDNA in `host` is already percent-encoded. That would still hold true for the path.

**Comment by phluid61** [comment]
Resolved by e8b5c99
